[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "accelerometer=*, gyroscope=*"
    Feature-Policy = "accelerometer 'self'; gyroscope 'self'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
